### ISSUE TITLE
Зависание на стандартном компиляторе

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/mxINI#2]
Последняя версия инклуда не компилируется, вешая дефолтный pawn компилятор (который идёт вместе с самп сервером). После некоторых поисков понял, что проблема появилась начиная с [этого](https://github.com/Open-GTO/mxINI/commit/c0e299460b21aadbb59296e079d77d39a84527a2) коммита и лежит в функции "ini_getErrorInfo" (в самом конце файла). При возвращении temp массива, записи в него текста и возврате самого массива компиляция проходит успешно, проблемы именно при возврате строк напрямую.

Воспроизводится с любой кодировкой файла инклуда (будь то UTF-8 или ANSI).

**Comment by twezyzcerrin** [comment]
have problem in compile  error 020: invalid symbol name ""

**Comment by ziggi** [comment]
> have problem in compile  error 020: invalid symbol name ""

Show your full compiler output

**Comment by twezyzcerrin** [comment]
give me you discord or come vk

**Comment by twezyzcerrin** [comment]
https://vk.com/mich0a come for show error

**Comment by twezyzcerrin** [comment]
![image](https://github.com/Open-GTO/mxINI/assets/111304290/614c1f4c-13cc-4e38-9484-9e3db8aaf207)

**Comment by twezyzcerrin** [comment]
> > have problem in compile  error 020: invalid symbol name ""
> 
> Show your full compiler output
![image](https://github.com/Open-GTO/mxINI/assets/111304290/6d6c14dd-e761-461d-be8c-46491a2be7d6)

**Comment by ziggi** [comment]
Не знаю, скачай последний `mxINI.inc` и замени им. Проверь кодировку (должна быть windows-1251).

**Comment by twezyzcerrin** [comment]
> Не знаю, скачай последний `mxINI.inc` и замени им. Проверь кодировку (должна быть windows-1251).
i ts lastest include ? give me your discord for contact you
